### PR TITLE
Remove python install step in Dockerfile

### PR DESCRIPTION
**Pull request by yuvipanda**
This is already installed upstream, in
https://github.com/jupyterhub/repo2docker/blob/main/Dockerfile

### CODE REVIEW

**Comment by hamelsmu** [comment]
LGTM

**Comment by yuvipanda** [comment]
Thanks, @hamelsmu! \o/

**Comment by UncleCJ** [comment]
Sorry, unintentionally commented on the commit...

Do I have [a crufty setup](https://github.com/UncleCJ/advent-of-code/blob/cj/.github/workflows/binder.yaml) (done ages ago) or did this actually break something supposed to work in my pipeline?

    Removing login credentials for https://index.docker.io/v1/
    0b6c26d149a5: Pulling from ***/advent-of-code
    Digest: sha256:037860d1e04bbebd3f075f6600b33857528046ff9f9be76bccc1d7ef84a5e771
    Status: Image is up to date for ***/advent-of-code:0b6c26d149a5
    docker.io/***/advent-of-code:0b6c26d149a5
    /create_docker_image.sh: line 190: python: command not found
    Verified that ***/advent-of-code:0b6c26d149a5 is publicly visible.

**Comment by dg-data** [comment]
It's broken, create_docker_image.sh tries using python the PR removed when your repo is Binder cached.
Quick fix is to update SHA (from the Github action log) in your Dockerfile in your-repo/binder directory.
Which ironically warns NOT TO EDIT THAT FILE :)

**Comment by yuvipanda** [comment]
@dg-data I've reverted this change for now, will investigate deeper later!

**Pull request merged**
