### PR TITLE
Fixes invalid yaml in README

### PR DESCRIPTION
**Pull request by arokem**

### CODE REVIEW

**Comment by choldgraf** [comment]
I was curious why the tests were failing with this one. @hamelsmu were those expected failures?

**Comment by hamelsmu** [comment]
Yeah when the pull request comes from a fork I can't do a dockerhub push test because those credentials are not available to the fork.  I'm still thinking about how to do this test in a secure not completely sure let me know if you have any thoughts

**Comment by choldgraf** [comment]
Hmmm I believe that we use `git-crypt` for this kinda thing? Maybe @consideRatio knows what's up there?

**Comment by consideRatio** [comment]
Hmmm, anything that we run as part of a PR that requires `docker push` credentials could be compromised quite easily I think, so it would make sense to use a dummy docker repository instead then perhaps.

I'm not read up on the tests and what they would catch, but do we really want to test a `docker push` action as part of PR tests? Hmmm... I figure this is a git repo for a GitHub action that is typically running on merges to master in another repo and pushes to some docker image registry, so, to test this repo you may want to do that.

I don't think we should push anything to the official `jupyterhub` org as part of PR tests, because it seems legit if you have an image named `jupyterhub/some-name`, but if we setup something like `jupyterhub-unsafe-testing/some-name` or `jupyterhub/unsafe-image-push-test:some-tag` its a different matter and we could perhaps make such push-credentials public even?

**Comment by manics** [comment]
Is it feasible to run a local Docker registry inside the test environment? https://docs.docker.com/registry/deploying/

**Comment by consideRatio** [comment]
@manics I'd say so, because k3d for example can do it quite easily by providing a `--enable-registry` flag, so I think it's should be doable.

**Comment by hamelsmu** [comment]
Running a local Docker registry in the test environment is a genius idea!!! That is a great solution!  Ok when I have time next week I can work on this.

**Pull request merged**
