### PR TITLE
Docker run tests defined in `image-tests` as root user

### LINKED ISSUE #110: Running tests defined in `image-tests` fail when `REPO_DIR` is not chowned by user
**Describe the bug**
I defined `REPO_DIR=/srv/repo` and the repo2docker action chowns this to the `root` user. Therefore in the action, when using `docker run` for `pytest`ing files in `image-tests`, this also needs to be run with the `-u root` rather than the `-u 1000` flag so that the `REPO_DIR` is read-writable, which is required for generating a `.pytest_cache` folder.

**To Reproduce**
1. Define `REPO_DIR=/srv/repo`
2. Add test to `image-tests`
3. Push to remote repo to trigger repo2docker action

```bash
   ../../opt/conda/lib/python3.11/site-packages/_pytest/stepwise.py:57
    /opt/conda/lib/python3.11/site-packages/_pytest/stepwise.py:57: PytestCacheWarning: could not create cache path /srv/repo/image-tests/.pytest_cache/v/cache/stepwise: [Errno 13] Permission denied: '/srv/repo/image-tests/.pytest_cache'
      session.config.cache.set(STEPWISE_CACHE_DIR, [])
```

### PR DESCRIPTION
**Pull request by jnywong**
Fixes #110

### CODE REVIEW

**Comment by jnywong** [comment]
Hmm, not sure why this change broke all the CI/CD tests...

**Comment by sgibson91** [comment]
The error is:

```
docker.errors.DockerException: invalid tag 'localhost:5000/repo2docker-test:43c232c553a9': invalid reference format
```

😕

**Comment by yuvipanda** [comment]
@jnywong https://github.com/jupyterhub/repo2docker-action/pull/118 should fix the failing tests once merged.

**Review by sgibson91 — APPROVED** [review]

**Comment by yuvipanda** [comment]
Sorry for not commenting on this earlier, but I don't think this will fix it. My *vague* understanding is that this *only* happens when using `Dockerfile`, and in that case perhaps what's needed is a `--chown` for the `COPY` step. repo2docker [does this](https://github.com/jupyterhub/repo2docker/blob/af6d3e844848dff84d6765de6c098a27465d1508/repo2docker/buildpacks/base.py#L155) automatically for non-Dockerfile uses, and we should *probably* document this for Dockerfile uses? I think @batpad did a little more investigation of this as well but it's not listed here.

I think running as root will break (or at least cause weird artifacts) for users that are using non-Dockerfile methods with repo2docker. For now, I'd like to revert this temporarily until we hear back from @batpad (or @sunu, who may have done the actual investigation). Sorry for not raising this earlier here :(

@jnywong @sgibson91 are you ok with reverting this?

**Comment by batpad** [comment]
So sorry for the delay commenting here - was hoping @sunu who looked into this could explain a bit better, but he's out sick today :(

I see the fix was to add something like this to the Dockerfile:

```
# enable image-tests; workaround for https://github.com/jupyterhub/repo2docker-action/issues/110
RUN chown -R ${NB_USER}:${NB_USER} /srv/repo

USER ${NB_USER}
```

You can see the Dockerfile here: https://github.com/sunu/ghg-workshop-python-image/blob/main/Dockerfile

Speaking to Yuvi a bit about this, it seems like we it maybe better to add this to the documentation as something you need to do if writing your own Dockerfile?

Apologies again for not commenting here earlier with a link to our workaround / fix in the Dockerfile!

**Comment by jnywong** [comment]
Thanks @yuvipanda for your insight here, I trust that you know better and happy to help with documenting workarounds 👍

**Comment by yuvipanda** [comment]
@batpad @sunu I *think* if https://github.com/sunu/ghg-workshop-python-image/pull/1 passes tests, then we can add documentation to https://github.com/jupyterhub/repo2docker-action?tab=readme-ov-file#testing-the-built-image to the effect of:

1. If you're using a `Dockerfile`, you need to copy `image-tests` into the docker image yourself
2. You *have* to make sure the ownership of that is 'correct', and suggest using `COPY --chown` for that

**Pull request merged**
